spring:
  datasource:
    url: jdbc:postgresql://localhost:26257/backend_test?sslmode=disable
    username: root
    password: 
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update